"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'boseservicecenter.co.in,www.boseservicecenter.co.in').split(',')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)yf4r)4%g@iifsz8+o5@-ahl!fq6yqup4!#s6&9c0sm5+zc&1-'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = False

# ALLOWED_HOSTS = ['boseservicecenter.co.in', 'www.boseservicecenter.co.in','http://boseservicecenter.co.in','https://boseservicecenter.co.in','145.223.19.36']
ALLOWED_HOSTS = ['boseservicecenter.co.in', 'www.boseservicecenter.co.in','145.223.19.36']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'myapp',
    'rest_framework',
    'corsheaders',
]

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}


# from datetime import timedelta

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  
# }



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    "https://boseservicecenter.co.in",
    "https://www.boseservicecenter.co.in",
]


CORS_ALLOW_ALL_ORIGINS = True


ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # or cache, file, etc.

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': '',
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8',  # Use utf8 instead of utf8mb4
        },
    }
}


MAINTENANCE_MODE = False

AUTH_USER_MODEL = 'myapp.User'

# for testing

# for productions
CASHFREE_CLIENT_ID = ''
CASHFREE_SECRET_KEY =''

CASHFREE_SANDBOX = False
# settings.py
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True  # Only set this to True if your site is running over HTTPS
SESSION_COOKIE_SECURE = True



CSRF_TRUSTED_ORIGINS = [
    'https://payments.cashfree.com',
    'https://api.cashfree.com',
    'https://boseservicecenter.co.in',
]



SECURE_SSL_REDIRECT = False
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'





AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True



BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')




DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'







EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.hostinger.com'   
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = '' 
# EMAIL_HOST_PASSWORD = '[Mm3~OUg9z' 
EMAIL_HOST_PASSWORD = '' 
DEFAULT_FROM_EMAIL = '"Bose Sales" <sales@boseservicecenter.co.in>'





# Secondary Email Configuration
EMAIL_BACKEND_SECONDARY = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST_SECONDARY = 'smtp.hostinger.com'
EMAIL_PORT_SECONDARY = 465
EMAIL_USE_SSL_SECONDARY = True
EMAIL_HOST_USER_SECONDARY = ''
# EMAIL_HOST_PASSWORD_SECONDARY = '1*hE[LMD' 
EMAIL_HOST_PASSWORD_SECONDARY = '' 
# DEFAULT_FROM_EMAIL_SECONDARY = 'support@boseservicecenter.co.in'
DEFAULT_FROM_EMAIL_SECONDARY = '"Bose Support" <support@boseservicecenter.co.in>'


