# Generated by Django 5.1.2 on 2025-01-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('paid', 'Paid'), ('user_dropped', 'User Dropped'), ('incomplete', 'Incomplete')], default='pending', max_length=50),
        ),
    ]
