# Generated by Django 5.1.2 on 2025-01-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsitevisitservicecenter',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('incomplete', 'Incomplete')], default='pending', max_length=50),
        ),
    ]
