# Generated by Django 5.1.2 on 2025-06-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_onsitevisitservicecenter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentresponseonline',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentresponseonline',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentresponseonline',
            name='update_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
