# Generated by Django 5.1.2 on 2025-07-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_paymentresponseonline_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualDisabled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('device_serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('service_center_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('visit_type', models.CharField(blank=True, max_length=100, null=True)),
                ('visit_date', models.CharField(blank=True, max_length=50, null=True)),
                ('time_slot', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
